name: echo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.27.2
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.7.0
  firebase_messaging: ^14.8.0

  # State Management
  provider: ^6.1.2

  # Media
  image_picker: ^1.1.0
  camera: ^0.10.6 # Be sure to follow platform-specific setup instructions
  image: ^4.1.7
  audioplayers: ^6.0.0
  record: ^5.0.5

  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  haptic_feedback: ^0.6.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # To add custom fonts for the gothic theme, add a fonts section here.
  # For example:
  # fonts:
  #   - family: YourGothicFont
  #     fonts:
  #       - asset: assets/fonts/YourGothicFont-Regular.ttf
  #       - asset: assets/fonts/YourGothicFont-Bold.ttf
  #         weight: 700
