name: Raven
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: any

  # Firebase
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  firebase_messaging: any

  # State Management
  provider: any

  # Media
  image_picker: any
  camera: any # Be sure to follow platform-specific setup instructions
  image: any
  audioplayers: any
  record: any

  # Utilities
  intl: any
  path_provider: any
  permission_handler: any
  haptic_feedback: any
  shared_preferences: any
  vibration: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:
  uses-material-design: true